[default]
host = "120.25.202.18"
port = "3306"
database = "iris-admin"
user = "root"
password = "!Kuaiex*&^%$#@mysql"
charset = "utf8"
sql_log = true

MaxIdleConns = 10 #空闲时最大的连接数
MaxOpenConns = 100 #最大的连接数
